name: CI

on:
  push:
  pull_request:

jobs:
  rust-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: fmt
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy --all-features -- -D warnings
      - name: test
        run: cargo test --all-features -- --nocapture
      - name: build
        run: cargo build --release
      # Optionnel supply-chain:
      # - name: cargo-audit
      #   run: cargo install cargo-audit && cargo audit
      # - name: cargo-deny
      #   run: cargo install cargo-deny && cargo deny check
